### PR TITLE
Implement Chebychev 2D grid

### PR DESCRIPTION
**Pull request by mwaldleben**

### CODE REVIEW

**Comment by morwald** [comment]
# [Codecov](https://codecov.io/gh/morwald/NS2DBenchmarkSolver.jl/pull/1?src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Moritz) Report
Base: **100.00**% // Head: **0.00**% // Decreases project coverage by **`-100.00%`** :warning:
> Coverage data is based on head [(`61a1abe`)](https://codecov.io/gh/morwald/NS2DBenchmarkSolver.jl/pull/1?src=pr&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Moritz) compared to base [(`2898d19`)](https://codecov.io/gh/morwald/NS2DBenchmarkSolver.jl/commit/2898d19249ae47885ad37280b0fcf49dcf1f8ba3?el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Moritz).
> Patch coverage: 0.00% of modified lines in pull request are covered.

:mega: This organization is not using Codecov’s [GitHub App Integration](https://github.com/apps/codecov). We recommend you install it so Codecov can continue to function properly for your repositories. [Learn more](https://about.codecov.io/blog/codecov-is-updating-its-github-integration/?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Moritz)

<details><summary>Additional details and impacted files</summary>


```diff
@@             Coverage Diff              @@
##              main      #1        +/-   ##
============================================
- Coverage   100.00%   0.00%   -100.00%     
============================================
  Files            2       1         -1     
  Lines            3      12         +9     
============================================
- Hits             3       0         -3     
- Misses           0      12        +12     
```


| [Impacted Files](https://codecov.io/gh/morwald/NS2DBenchmarkSolver.jl/pull/1?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Moritz) | Coverage Δ | |
|---|---|---|
| [src/chebychev.jl](https://codecov.io/gh/morwald/NS2DBenchmarkSolver.jl/pull/1?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Moritz#diff-c3JjL2NoZWJ5Y2hldi5qbA==) | `0.00% <0.00%> (ø)` | |
| [src/NS2DBenchmarkSolver.jl](https://codecov.io/gh/morwald/NS2DBenchmarkSolver.jl/pull/1?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Moritz#diff-c3JjL05TMkRCZW5jaG1hcmtTb2x2ZXIuamw=) | | |

Help us with your feedback. Take ten seconds to tell us [how you rate us](https://about.codecov.io/nps?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Moritz). Have a feature suggestion? [Share it here.](https://app.codecov.io/gh/feedback/?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Moritz)

</details>

[:umbrella: View full report at Codecov](https://codecov.io/gh/morwald/NS2DBenchmarkSolver.jl/pull/1?src=pr&el=continue&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Moritz).   
:loudspeaker: Do you have feedback about the report comment? [Let us know in this issue](https://about.codecov.io/codecov-pr-comment-feedback/?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Moritz).

**Comment by morwald** [comment]
# [Codecov](https://codecov.io/gh/morwald/NS2DBenchmarkSolver.jl/pull/1?src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Moritz) Report
Base: **100.00**% // Head: **100.00**% // No change to project coverage :thumbsup:
> Coverage data is based on head [(`7b5eaff`)](https://codecov.io/gh/morwald/NS2DBenchmarkSolver.jl/pull/1?src=pr&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Moritz) compared to base [(`2898d19`)](https://codecov.io/gh/morwald/NS2DBenchmarkSolver.jl/commit/2898d19249ae47885ad37280b0fcf49dcf1f8ba3?el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Moritz).
> Patch coverage: 100.00% of modified lines in pull request are covered.

:mega: This organization is not using Codecov’s [GitHub App Integration](https://github.com/apps/codecov). We recommend you install it so Codecov can continue to function properly for your repositories. [Learn more](https://about.codecov.io/blog/codecov-is-updating-its-github-integration/?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Moritz)

<details><summary>Additional details and impacted files</summary>


```diff
@@            Coverage Diff            @@
##              main        #1   +/-   ##
=========================================
  Coverage   100.00%   100.00%           
=========================================
  Files            2         2           
  Lines            3        14   +11     
=========================================
+ Hits             3        14   +11     
```


| [Impacted Files](https://codecov.io/gh/morwald/NS2DBenchmarkSolver.jl/pull/1?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Moritz) | Coverage Δ | |
|---|---|---|
| [src/NS2DBenchmarkSolver.jl](https://codecov.io/gh/morwald/NS2DBenchmarkSolver.jl/pull/1?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Moritz#diff-c3JjL05TMkRCZW5jaG1hcmtTb2x2ZXIuamw=) | `100.00% <ø> (ø)` | |
| [src/diff.jl](https://codecov.io/gh/morwald/NS2DBenchmarkSolver.jl/pull/1?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Moritz#diff-c3JjL2RpZmYuamw=) | `100.00% <100.00%> (ø)` | |

Help us with your feedback. Take ten seconds to tell us [how you rate us](https://about.codecov.io/nps?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Moritz). Have a feature suggestion? [Share it here.](https://app.codecov.io/gh/feedback/?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Moritz)

</details>

[:umbrella: View full report at Codecov](https://codecov.io/gh/morwald/NS2DBenchmarkSolver.jl/pull/1?src=pr&el=continue&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Moritz).   
:loudspeaker: Do you have feedback about the report comment? [Let us know in this issue](https://about.codecov.io/codecov-pr-comment-feedback/?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Moritz).

**Comment by mwaldleben** [comment]
For now, Chebychev nodes and associated differentiation matrix available trough function `diffcheb`.

**Comment by morwald** [comment]
# [Codecov](https://codecov.io/gh/morwald/NS2DBenchmarkSolver.jl/pull/1?src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Moritz) Report
Base: **100.00**% // Head: **100.00**% // No change to project coverage :thumbsup:
> Coverage data is based on head [(`45e4929`)](https://codecov.io/gh/morwald/NS2DBenchmarkSolver.jl/pull/1?src=pr&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Moritz) compared to base [(`2898d19`)](https://codecov.io/gh/morwald/NS2DBenchmarkSolver.jl/commit/2898d19249ae47885ad37280b0fcf49dcf1f8ba3?el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Moritz).
> Patch coverage: 100.00% of modified lines in pull request are covered.

:mega: This organization is not using Codecov’s [GitHub App Integration](https://github.com/apps/codecov). We recommend you install it so Codecov can continue to function properly for your repositories. [Learn more](https://about.codecov.io/blog/codecov-is-updating-its-github-integration/?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Moritz)

<details><summary>Additional details and impacted files</summary>


```diff
@@            Coverage Diff            @@
##              main        #1   +/-   ##
=========================================
  Coverage   100.00%   100.00%           
=========================================
  Files            2         2           
  Lines            3        14   +11     
=========================================
+ Hits             3        14   +11     
```


| [Impacted Files](https://codecov.io/gh/morwald/NS2DBenchmarkSolver.jl/pull/1?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Moritz) | Coverage Δ | |
|---|---|---|
| [src/NS2DBenchmarkSolver.jl](https://codecov.io/gh/morwald/NS2DBenchmarkSolver.jl/pull/1?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Moritz#diff-c3JjL05TMkRCZW5jaG1hcmtTb2x2ZXIuamw=) | `100.00% <ø> (ø)` | |
| [src/diff.jl](https://codecov.io/gh/morwald/NS2DBenchmarkSolver.jl/pull/1?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Moritz#diff-c3JjL2RpZmYuamw=) | `100.00% <100.00%> (ø)` | |

Help us with your feedback. Take ten seconds to tell us [how you rate us](https://about.codecov.io/nps?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Moritz). Have a feature suggestion? [Share it here.](https://app.codecov.io/gh/feedback/?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Moritz)

</details>

[:umbrella: View full report at Codecov](https://codecov.io/gh/morwald/NS2DBenchmarkSolver.jl/pull/1?src=pr&el=continue&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Moritz).   
:loudspeaker: Do you have feedback about the report comment? [Let us know in this issue](https://about.codecov.io/codecov-pr-comment-feedback/?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Moritz).

**Pull request merged**
